package org.adhes.hemophilie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HematomeSuperficielAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomeSuperficielAllPropertiesEquals(HematomeSuperficiel expected, HematomeSuperficiel actual) {
        assertHematomeSuperficielAutoGeneratedPropertiesEquals(expected, actual);
        assertHematomeSuperficielAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomeSuperficielAllUpdatablePropertiesEquals(HematomeSuperficiel expected, HematomeSuperficiel actual) {
        assertHematomeSuperficielUpdatableFieldsEquals(expected, actual);
        assertHematomeSuperficielUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomeSuperficielAutoGeneratedPropertiesEquals(HematomeSuperficiel expected, HematomeSuperficiel actual) {
        assertThat(expected)
            .as("Verify HematomeSuperficiel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomeSuperficielUpdatableFieldsEquals(HematomeSuperficiel expected, HematomeSuperficiel actual) {
        assertThat(expected)
            .as("Verify HematomeSuperficiel relevant properties")
            .satisfies(e -> assertThat(e.getReponse()).as("check reponse").isEqualTo(actual.getReponse()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getSiege()).as("check siege").isEqualTo(actual.getSiege()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomeSuperficielUpdatableRelationshipsEquals(HematomeSuperficiel expected, HematomeSuperficiel actual) {
        // empty method
    }
}
