package org.adhes.hemophilie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HematomePsoasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomePsoasAllPropertiesEquals(HematomePsoas expected, HematomePsoas actual) {
        assertHematomePsoasAutoGeneratedPropertiesEquals(expected, actual);
        assertHematomePsoasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomePsoasAllUpdatablePropertiesEquals(HematomePsoas expected, HematomePsoas actual) {
        assertHematomePsoasUpdatableFieldsEquals(expected, actual);
        assertHematomePsoasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomePsoasAutoGeneratedPropertiesEquals(HematomePsoas expected, HematomePsoas actual) {
        assertThat(expected)
            .as("Verify HematomePsoas auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomePsoasUpdatableFieldsEquals(HematomePsoas expected, HematomePsoas actual) {
        assertThat(expected)
            .as("Verify HematomePsoas relevant properties")
            .satisfies(e -> assertThat(e.getReponse()).as("check reponse").isEqualTo(actual.getReponse()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getRecidive()).as("check recidive").isEqualTo(actual.getRecidive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHematomePsoasUpdatableRelationshipsEquals(HematomePsoas expected, HematomePsoas actual) {
        // empty method
    }
}
