package org.adhes.hemophilie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HemarthroseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemarthroseAllPropertiesEquals(Hemarthrose expected, Hemarthrose actual) {
        assertHemarthroseAutoGeneratedPropertiesEquals(expected, actual);
        assertHemarthroseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemarthroseAllUpdatablePropertiesEquals(Hemarthrose expected, Hemarthrose actual) {
        assertHemarthroseUpdatableFieldsEquals(expected, actual);
        assertHemarthroseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemarthroseAutoGeneratedPropertiesEquals(Hemarthrose expected, Hemarthrose actual) {
        assertThat(expected)
            .as("Verify Hemarthrose auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemarthroseUpdatableFieldsEquals(Hemarthrose expected, Hemarthrose actual) {
        assertThat(expected)
            .as("Verify Hemarthrose relevant properties")
            .satisfies(e -> assertThat(e.getReponse()).as("check reponse").isEqualTo(actual.getReponse()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getSiege()).as("check siege").isEqualTo(actual.getSiege()))
            .satisfies(e -> assertThat(e.getFrequencePerAn()).as("check frequencePerAn").isEqualTo(actual.getFrequencePerAn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemarthroseUpdatableRelationshipsEquals(Hemarthrose expected, Hemarthrose actual) {
        // empty method
    }
}
