package org.adhes.hemophilie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HemorragiesCutaneoMuqueusesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemorragiesCutaneoMuqueusesAllPropertiesEquals(
        HemorragiesCutaneoMuqueuses expected,
        HemorragiesCutaneoMuqueuses actual
    ) {
        assertHemorragiesCutaneoMuqueusesAutoGeneratedPropertiesEquals(expected, actual);
        assertHemorragiesCutaneoMuqueusesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemorragiesCutaneoMuqueusesAllUpdatablePropertiesEquals(
        HemorragiesCutaneoMuqueuses expected,
        HemorragiesCutaneoMuqueuses actual
    ) {
        assertHemorragiesCutaneoMuqueusesUpdatableFieldsEquals(expected, actual);
        assertHemorragiesCutaneoMuqueusesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemorragiesCutaneoMuqueusesAutoGeneratedPropertiesEquals(
        HemorragiesCutaneoMuqueuses expected,
        HemorragiesCutaneoMuqueuses actual
    ) {
        assertThat(expected)
            .as("Verify HemorragiesCutaneoMuqueuses auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemorragiesCutaneoMuqueusesUpdatableFieldsEquals(
        HemorragiesCutaneoMuqueuses expected,
        HemorragiesCutaneoMuqueuses actual
    ) {
        assertThat(expected)
            .as("Verify HemorragiesCutaneoMuqueuses relevant properties")
            .satisfies(e -> assertThat(e.getReponse()).as("check reponse").isEqualTo(actual.getReponse()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getFrequencePerAn()).as("check frequencePerAn").isEqualTo(actual.getFrequencePerAn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHemorragiesCutaneoMuqueusesUpdatableRelationshipsEquals(
        HemorragiesCutaneoMuqueuses expected,
        HemorragiesCutaneoMuqueuses actual
    ) {
        // empty method
    }
}
