package org.adhes.hemophilie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SaignementSNCAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaignementSNCAllPropertiesEquals(SaignementSNC expected, SaignementSNC actual) {
        assertSaignementSNCAutoGeneratedPropertiesEquals(expected, actual);
        assertSaignementSNCAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaignementSNCAllUpdatablePropertiesEquals(SaignementSNC expected, SaignementSNC actual) {
        assertSaignementSNCUpdatableFieldsEquals(expected, actual);
        assertSaignementSNCUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaignementSNCAutoGeneratedPropertiesEquals(SaignementSNC expected, SaignementSNC actual) {
        assertThat(expected)
            .as("Verify SaignementSNC auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaignementSNCUpdatableFieldsEquals(SaignementSNC expected, SaignementSNC actual) {
        assertThat(expected)
            .as("Verify SaignementSNC relevant properties")
            .satisfies(e -> assertThat(e.getReponse()).as("check reponse").isEqualTo(actual.getReponse()))
            .satisfies(e -> assertThat(e.getEvolution()).as("check evolution").isEqualTo(actual.getEvolution()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaignementSNCUpdatableRelationshipsEquals(SaignementSNC expected, SaignementSNC actual) {
        // empty method
    }
}
