import dayjs from 'dayjs/esm';
import { IHemarthrose } from 'app/entities/hemarthrose/hemarthrose.model';
import { IHematomeSuperficiel } from 'app/entities/hematome-superficiel/hematome-superficiel.model';
import { IHematomePsoas } from 'app/entities/hematome-psoas/hematome-psoas.model';
import { IHemorragiesCutaneoMuqueuses } from 'app/entities/hemorragies-cutaneo-muqueuses/hemorragies-cutaneo-muqueuses.model';
import { IHemorragieVisceres } from 'app/entities/hemorragie-visceres/hemorragie-visceres.model';
import { ISaignementSNC } from 'app/entities/saignement-snc/saignement-snc.model';
import { IUser } from 'app/entities/user/user.model';
import { IPatient } from 'app/entities/patient/patient.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { FormeHemophilie } from 'app/entities/enumerations/forme-hemophilie.model';
import { TestStatus } from 'app/entities/enumerations/test-status.model';
import { CircumstanceDecouverte } from 'app/entities/enumerations/circumstance-decouverte.model';
import { PriseEnChargeType } from 'app/entities/enumerations/prise-en-charge-type.model';
import { InjectionType } from 'app/entities/enumerations/injection-type.model';
import { TraitementType } from 'app/entities/enumerations/traitement-type.model';
import { TestResult } from 'app/entities/enumerations/test-result.model';
import { VieSocialeStatus } from 'app/entities/enumerations/vie-sociale-status.model';

export interface IFiche {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  anneeDiagnostic?: number | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  consentementRegistre?: boolean | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: string | null;
  casSimilairesFamille?: keyof typeof OuiNonNP | null;
  nbreCasSimilaires?: number | null;
  degreParenteCasSimilaires?: string | null;
  casDecesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nbreCasDeces?: number | null;
  formeHemophilie?: keyof typeof FormeHemophilie | null;
  nbreFreres?: number | null;
  nbreSoeurs?: number | null;
  dateTestConfirmation?: dayjs.Dayjs | null;
  hemogrammeHb?: number | null;
  hemogrammeHt?: number | null;
  plaquettes?: number | null;
  tp?: number | null;
  fibrinogene?: number | null;
  tcaMT?: number | null;
  tcaMT2h?: number | null;
  tcaTemoin2h?: number | null;
  ts?: keyof typeof TestStatus | null;
  circumstanceDecouverte?: keyof typeof CircumstanceDecouverte | null;
  date1erSigneClinique?: dayjs.Dayjs | null;
  ageDiagnostic?: number | null;
  priseEnCharge?: keyof typeof PriseEnChargeType | null;
  causePriseEnCharge?: string | null;
  doseProphylaxie?: string | null;
  frequenceProphylaxie?: number | null;
  debutProphylaxie?: dayjs.Dayjs | null;
  modaliteInjection?: keyof typeof InjectionType | null;
  typeTraitementSubstitutif?: keyof typeof TraitementType | null;
  age1ereSubstitution?: number | null;
  psl?: keyof typeof OuiNonNP | null;
  plasmaFraisCongele?: keyof typeof OuiNonNP | null;
  cryoprecipite?: keyof typeof OuiNonNP | null;
  complicationsOrthopediques?: keyof typeof OuiNonNP | null;
  complicationInhibiteurs?: keyof typeof OuiNonNP | null;
  testRecuperationFAH?: keyof typeof TestStatus | null;
  resultatTestRecuperation?: keyof typeof TestResult | null;
  vieSociale?: keyof typeof VieSocialeStatus | null;
  etatMarital?: keyof typeof OuiNonNP | null;
  enfants?: keyof typeof OuiNonNP | null;
  handicap?: keyof typeof OuiNonNP | null;
  typeHandicap?: string | null;
  activiteSportive?: keyof typeof OuiNonNP | null;
  typeActiviteSportive?: string | null;
  decede?: keyof typeof OuiNonNP | null;
  causeDateDeces?: string | null;
  hemarthrose?: Pick<IHemarthrose, 'id'> | null;
  hematomeSuperficiel?: Pick<IHematomeSuperficiel, 'id'> | null;
  hematomePsoas?: Pick<IHematomePsoas, 'id'> | null;
  hemorragiesCutaneoMuqueuses?: Pick<IHemorragiesCutaneoMuqueuses, 'id'> | null;
  hemorragieVisceres?: Pick<IHemorragieVisceres, 'id'> | null;
  saignementSNC?: Pick<ISaignementSNC, 'id'> | null;
  user?: Pick<IUser, 'id'> | null;
  patient?: Pick<IPatient, 'id'> | null;
}

export type NewFiche = Omit<IFiche, 'id'> & { id: null };
