import dayjs from 'dayjs/esm';

import { IFiche, NewFiche } from './fiche.model';

export const sampleWithRequiredData: IFiche = {
  id: 24690,
  dossierNumber: 'lors au-dedans de personnel professionnel',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  priseEnCharge: 'A_LA_DEMANDE',
};

export const sampleWithPartialData: IFiche = {
  id: 19189,
  dossierNumber: 'ensuite',
  indexNumber: 'à condition que dorénavant de peur que',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'secours',
  degreParenteCasSimilaires: 'main-d’œuvre',
  casDecesSyndromeHemorragique: 'NP',
  nbreCasDeces: 28330,
  hemogrammeHt: 11324.67,
  plaquettes: 9195,
  tp: 6841.81,
  fibrinogene: 24735.89,
  tcaTemoin2h: 20679.27,
  ts: 'NORMAL',
  circumstanceDecouverte: 'SYNDROME_HEMORRAGIQUE',
  date1erSigneClinique: dayjs('2024-11-02'),
  ageDiagnostic: 12016,
  priseEnCharge: 'PROPHYLAXIE',
  doseProphylaxie: 'hirsute',
  frequenceProphylaxie: 8592,
  typeTraitementSubstitutif: 'PLASMATIQUE',
  cryoprecipite: 'OUI',
  vieSociale: 'PRESCOLAIRE',
  etatMarital: 'NP',
  enfants: 'NP',
  typeHandicap: 'sitôt que',
  activiteSportive: 'NON',
  typeActiviteSportive: 'racheter rentrer du moment que',
  causeDateDeces: 'considérable relier',
};

export const sampleWithFullData: IFiche = {
  id: 15993,
  dossierNumber: 'avant-hier',
  ordreNumber: 'hi',
  indexNumber: 'mature',
  anneeDiagnostic: 6543,
  diagnostic: 'WILLEBRAND',
  autreDiagnostic: 'déshabiller jusque adepte',
  dateEnregistrementRegistre: dayjs('2024-11-02'),
  consentementRegistre: false,
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'moyennant secouriste',
  casSimilairesFamille: 'OUI',
  nbreCasSimilaires: 14121,
  degreParenteCasSimilaires: 'au prix de dring bè',
  casDecesSyndromeHemorragique: 'NON',
  nbreCasDeces: 32671,
  formeHemophilie: 'HEREDITAIRE',
  nbreFreres: 7496,
  nbreSoeurs: 4345,
  dateTestConfirmation: dayjs('2024-11-03'),
  hemogrammeHb: 10115.94,
  hemogrammeHt: 2660.29,
  plaquettes: 27696,
  tp: 25396.65,
  fibrinogene: 4482.14,
  tcaMT: 32421.1,
  tcaMT2h: 18915.26,
  tcaTemoin2h: 22524.78,
  ts: 'NON_FAIT',
  circumstanceDecouverte: 'FAMILIALE',
  date1erSigneClinique: dayjs('2024-11-03'),
  ageDiagnostic: 31283,
  priseEnCharge: 'PROPHYLAXIE',
  causePriseEnCharge: 'sitôt que tellement',
  doseProphylaxie: 'partenaire apporter miam',
  frequenceProphylaxie: 22369,
  debutProphylaxie: dayjs('2024-11-03'),
  modaliteInjection: 'AUTO_INJECTION',
  typeTraitementSubstitutif: 'RECOMBINANT',
  age1ereSubstitution: 9497,
  psl: 'OUI',
  plasmaFraisCongele: 'OUI',
  cryoprecipite: 'NON',
  complicationsOrthopediques: 'NON',
  complicationInhibiteurs: 'NON',
  testRecuperationFAH: 'NON_FAIT',
  resultatTestRecuperation: 'NORMAL',
  vieSociale: 'TRAVAILLE',
  etatMarital: 'OUI',
  enfants: 'NP',
  handicap: 'OUI',
  typeHandicap: 'maintenant',
  activiteSportive: 'OUI',
  typeActiviteSportive: 'si hôte',
  decede: 'OUI',
  causeDateDeces: 'si autour de',
};

export const sampleWithNewData: NewFiche = {
  dossierNumber: 'puisque sans doute',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  priseEnCharge: 'A_LA_DEMANDE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
